### ISSUE TITLE
`show.grid.lines` not functional for `scatterPlot`

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoViz#15]
E.g. `scatterPlot(example_df, x.by = "PC1", y.by = "PC2", show.grid.lines = FALSE)`:
![image](https://github.com/dtm2451/dittoViz/assets/10225716/a1385fdc-f74b-41fd-b794-b454740fcfd0)

**Comment by dtm2451** [comment]
Simple fix, that I've pushed right on through.
