### ISSUE TITLE
`multivar.split.dir` clarification in `scatterPlot`

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoViz#16]
Is this parameter functional at all since multiple vars can't be given to `x.by` or `y.by`?

**Comment by dtm2451** [comment]
It's for the combination of giving multiple `var`s as well as something else to `split.by`.

**Comment by j-andrews7** [comment]
Ahh, I see, I didn't realize multiple vars to `color.by` was supported, my bad.
